# Generated by Django 6.0 on 2026-07-11 08:17

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='ترتیب')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'زنگ',
                'verbose_name_plural': 'زنگ ها',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنج\u200cشنبه')], verbose_name='روز هفته')),
                ('week_type', models.IntegerField(choices=[(1, 'هفته اول'), (2, 'هفته دوم'), (3, 'هر دو هفته')], default=3, verbose_name='نوع هفته')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('bell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_schedules', to='scheduling.bell', verbose_name='زنگ')),
            ],
            options={
                'verbose_name': 'برنامه کلاسی',
                'verbose_name_plural': 'برنامه\u200cهای کلاسی',
                'ordering': ['day_of_week', 'bell__order'],
            },
        ),
    ]
