# Generated by Django 6.0 on 2026-07-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='class_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='school.classsubject', verbose_name='درس کلاس'),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.UniqueConstraint(fields=('class_subject', 'day_of_week', 'week_type', 'bell'), name='unique_class_schedule_slot'),
        ),
    ]
