# Generated by Django 6.0 on 2026-09-24 16:23

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import website.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_branch_access_derived_from_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('show_hero_slider', models.BooleanField(default=True, verbose_name='نمایش اسلایدر بالای صفحه')),
                ('show_intro', models.BooleanField(default=True, verbose_name='نمایش سکشن معرفی')),
                ('show_features', models.BooleanField(default=True, verbose_name='نمایش سکشن «چرا ما»')),
                ('show_learning', models.BooleanField(default=True, verbose_name='نمایش سکشن یادگیری فعال')),
                ('show_teachers', models.BooleanField(default=True, verbose_name='نمایش سکشن اساتید')),
                ('intro_title', models.TextField(default='آینده\u200cای درخشان برای\nفرزند شما در مدرسه نسل قلم', help_text='با Enter می\u200cتوانید عنوان را دو خطی کنید.', max_length=200, verbose_name='عنوان')),
                ('intro_text', models.TextField(default='ما با ایجاد محیطی شاد، خلاق و امن، اشتیاق به یادگیری را در کودکان پرورش می\u200cدهیم تا با اعتماد به نفس برای چالش\u200cهای فردا آماده شوند.', verbose_name='توضیح')),
                ('intro_image', models.ImageField(blank=True, help_text='ابعاد پیشنهادی ۷۰۰×۷۰۰ (PNG با پس\u200cزمینه شفاف) پیکسل؛ jpg، png یا webp، حداکثر ۲ مگابایت.', upload_to='website/intro/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.validators.validate_image_size], verbose_name='تصویر')),
                ('intro_image_alt', models.CharField(blank=True, help_text='توضیح کوتاه تصویر برای نابینایان و موتورهای جستجو.', max_length=150, verbose_name='متن جایگزین تصویر (alt)')),
                ('intro_primary_text', models.CharField(blank=True, default='ثبت نام کنید', max_length=40, verbose_name='متن دکمه اول')),
                ('intro_primary_url', models.CharField(blank=True, default='#', max_length=300, validators=[website.validators.validate_link], verbose_name='لینک دکمه اول')),
                ('intro_secondary_text', models.CharField(blank=True, default='بازدید از مدرسه', max_length=40, verbose_name='متن دکمه دوم')),
                ('intro_secondary_url', models.CharField(blank=True, default='#', max_length=300, validators=[website.validators.validate_link], verbose_name='لینک دکمه دوم')),
                ('features_title', models.CharField(default='چرا مدرسه نسل قلم؟', max_length=150, verbose_name='عنوان')),
                ('features_subtitle', models.TextField(blank=True, default='ما با بهره\u200cگیری از جدیدترین متدهای آموزشی و محیطی پویا، استعدادهای نهفته کودکان را کشف و شکوفا می\u200cکنیم.', verbose_name='زیرعنوان')),
                ('learning_title', models.CharField(default='یادگیری فعال، ارتباط با اعتماد به نفس', max_length=150, verbose_name='عنوان')),
                ('learning_subtitle', models.TextField(blank=True, default='ما به کودکان کمک می\u200cکنیم تا با روش\u200cهای خلاقانه و تعاملی، مهارت\u200cهای لازم برای آینده را کسب کنند.', verbose_name='زیرعنوان')),
                ('learning_image', models.ImageField(blank=True, help_text='ابعاد پیشنهادی ۷۰۰×۶۴۰ پیکسل؛ jpg، png یا webp، حداکثر ۲ مگابایت.', upload_to='website/learning/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.validators.validate_image_size], verbose_name='تصویر')),
                ('learning_image_alt', models.CharField(blank=True, help_text='توضیح کوتاه تصویر برای نابینایان و موتورهای جستجو.', max_length=150, verbose_name='متن جایگزین تصویر (alt)')),
                ('teachers_title', models.CharField(default='اساتید مجرب ما', max_length=150, verbose_name='عنوان')),
                ('teachers_subtitle', models.TextField(blank=True, default='با اساتید متخصص و متعهد مدرسه پیشرو آشنا شوید', verbose_name='زیرعنوان')),
            ],
            options={
                'verbose_name': 'مدیریت صفحه اصلی',
                'verbose_name_plural': 'مدیریت صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('site_name', models.CharField(default='مدرسه نسل قلم', max_length=100, verbose_name='نام سایت')),
                ('logo', models.ImageField(blank=True, help_text='اختیاری. PNG یا WebP با پس\u200cزمینه شفاف، حدود ۲۴۰×۸۰ پیکسل. اگر خالی باشد، نام سایت نمایش داده می\u200cشود.', upload_to='website/logo/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.validators.validate_image_size], verbose_name='لوگو')),
                ('login_text', models.CharField(default='ورود', max_length=30, verbose_name='متن دکمه ورود')),
                ('login_url', models.CharField(blank=True, help_text='اگر خالی باشد، به صفحه ورود سامانه می\u200cرود.', max_length=300, validators=[website.validators.validate_link], verbose_name='لینک دکمه ورود')),
                ('copyright_text', models.CharField(default='تمامی حقوق برای مدرسه نسل قلم محفوظ است.', max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('footer_note', models.CharField(blank=True, default='Made with 💗 in Urmia', max_length=200, verbose_name='متن پایین فوتر')),
                ('meta_title', models.CharField(blank=True, help_text='عنوان تب مرورگر و نتایج گوگل. اگر خالی باشد، نام سایت استفاده می\u200cشود.', max_length=70, verbose_name='عنوان صفحه (meta title)')),
                ('meta_description', models.CharField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر؛ در نتایج جستجو زیر عنوان نمایش داده می\u200cشود.', max_length=160, verbose_name='توضیح صفحه (meta description)')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('badge_text', models.CharField(blank=True, max_length=60, verbose_name='متن برچسب')),
                ('badge_emoji', models.CharField(blank=True, help_text='مثال: 🎨', max_length=10, verbose_name='ایموجی برچسب')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('button_text', models.CharField(blank=True, max_length=40, verbose_name='متن دکمه')),
                ('button_url', models.CharField(blank=True, default='#', max_length=300, validators=[website.validators.validate_link], verbose_name='لینک دکمه')),
                ('image', models.ImageField(blank=True, help_text='ابعاد پیشنهادی ۱۶۰۰×۶۰۰ (افقی؛ سوژه اصلی سمت چپ تصویر) پیکسل؛ jpg، png یا webp، حداکثر ۲ مگابایت.', upload_to='website/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.validators.validate_image_size], verbose_name='تصویر پس\u200cزمینه')),
                ('image_alt', models.CharField(blank=True, help_text='توضیح کوتاه تصویر برای نابینایان و موتورهای جستجو.', max_length=150, verbose_name='متن جایگزین تصویر (alt)')),
                ('overlay_color', models.CharField(choices=[('orange', 'نارنجی'), ('blue', 'آبی'), ('teal', 'سبزآبی'), ('purple', 'بنفش')], default='orange', max_length=10, verbose_name='رنگ لایه روی تصویر')),
                ('static_fallback', models.CharField(blank=True, editable=False, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='website.landingpage', verbose_name='صفحه اصلی')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدهای بالای صفحه',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('image', models.ImageField(blank=True, help_text='ابعاد پیشنهادی ۴۰۰×۴۰۰ (مربع) پیکسل؛ jpg، png یا webp، حداکثر ۲ مگابایت.', upload_to='website/features/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.validators.validate_image_size], verbose_name='تصویر')),
                ('image_alt', models.CharField(blank=True, help_text='توضیح کوتاه تصویر برای نابینایان و موتورهای جستجو.', max_length=150, verbose_name='متن جایگزین تصویر (alt)')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('static_fallback', models.CharField(blank=True, editable=False, max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.landingpage', verbose_name='صفحه اصلی')),
            ],
            options={
                'verbose_name': 'کارت «چرا ما»',
                'verbose_name_plural': 'کارت\u200cهای «چرا ما»',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('name_override', models.CharField(blank=True, help_text='اگر خالی باشد، نام حساب کاربری استاد نمایش داده می\u200cشود.', max_length=100, verbose_name='نام نمایشی')),
                ('photo_override', models.ImageField(blank=True, help_text='ابعاد پیشنهادی ۳۹۰×۴۵۰ (عمودی) پیکسل؛ jpg، png یا webp، حداکثر ۲ مگابایت.', upload_to='website/teachers/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.validators.validate_image_size], verbose_name='عکس')),
                ('specialty_override', models.CharField(blank=True, help_text='مثال: استاد علوم. اگر خالی باشد، رشته تحصیلی استاد نمایش داده می\u200cشود.', max_length=80, verbose_name='عنوان تخصص')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='website.landingpage', verbose_name='صفحه اصلی')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_cards', to='staff.teacherprofile', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'استاد صفحه اصلی',
                'verbose_name_plural': 'اساتید صفحه اصلی',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('icon_emoji', models.CharField(blank=True, help_text='مثال: 👑', max_length=10, verbose_name='ایموجی آیکون')),
                ('icon_image', models.ImageField(blank=True, help_text='ابعاد پیشنهادی ۹۶×۹۶ پیکسل؛ jpg، png یا webp، حداکثر ۲ مگابایت.', upload_to='website/learning/icons/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.validators.validate_image_size], verbose_name='تصویر آیکون')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='زیرعنوان')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_points', to='website.landingpage', verbose_name='صفحه اصلی')),
            ],
            options={
                'verbose_name': 'آیتم یادگیری فعال',
                'verbose_name_plural': 'آیتم\u200cهای یادگیری فعال',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url', models.CharField(default='#', help_text='مثال: /auth/login/ یا #contact یا https://instagram.com/...', max_length=300, validators=[website.validators.validate_link], verbose_name='لینک')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='website.sitesettings', verbose_name='تنظیمات سایت')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('url', models.CharField(default='#', help_text='مثال: /auth/login/ یا #contact یا https://instagram.com/...', max_length=300, validators=[website.validators.validate_link], verbose_name='لینک')),
                ('kind', models.CharField(choices=[('social', 'شبکه اجتماعی'), ('page', 'صفحه')], default='page', max_length=10, verbose_name='نوع')),
                ('icon', models.CharField(blank=True, choices=[('fa-brands fa-instagram', 'اینستاگرام'), ('fa-brands fa-telegram', 'تلگرام'), ('fa-brands fa-whatsapp', 'واتساپ'), ('fa-brands fa-x-twitter', 'ایکس (توییتر)'), ('fa-solid fa-circle-play', 'ویدیو (آپارات / یوتیوب)'), ('fa-solid fa-phone', 'تلفن'), ('fa-solid fa-envelope', 'ایمیل'), ('fa-solid fa-location-dot', 'آدرس'), ('fa-solid fa-circle-info', 'اطلاعات'), ('fa-solid fa-circle-question', 'سوال')], max_length=40, verbose_name='آیکون')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='website.sitesettings', verbose_name='تنظیمات سایت')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک\u200cهای فوتر',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
