# Generated by Django 6.0 on 2026-07-11 08:17

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(max_length=20, unique=True, verbose_name='کد پرسنلی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('hire_date', django_jalali.db.models.jDateField(verbose_name='تاریخ استخدام')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس اضطراری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='مدرک تحصیلی')),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True, verbose_name='رشته تحصیلی')),
                ('teaching_experience', models.PositiveIntegerField(default=0, verbose_name='سابقه تدریس (سال)')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(limit_choices_to={'user__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='staff.staff', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'پروفایل معلم',
                'verbose_name_plural': 'پروفایل معلمان',
                'ordering': ['staff__user__last_name', 'staff__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='BranchAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='شعبه پیش\u200cفرض')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_accesses', to='school.branch', verbose_name='شعبه')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_accesses', to='staff.staff', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'دسترسی به شعبه',
                'verbose_name_plural': 'دسترسی\u200cهای شعبه',
                'constraints': [models.UniqueConstraint(fields=('staff', 'branch'), name='unique_staff_branch_access')],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع همکاری')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان همکاری')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('transferred', 'منتقل شده'), ('terminated', 'پایان همکاری'), ('leave', 'مرخصی')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='school.academicyear', verbose_name='سال تحصیلی')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='school.branch', verbose_name='شعبه')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='staff.teacherprofile', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'انتساب معلم',
                'verbose_name_plural': 'انتساب معلمان',
                'ordering': ['-academic_year__start_date', 'teacher__staff__user__last_name', 'teacher__staff__user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'branch', 'academic_year'), name='unique_teacher_branch_year')],
            },
        ),
    ]
