# Generated by Django 6.0 on 2026-09-26 22:40

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_branch_access_derived_from_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], default='', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='personnel_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد پرسنلی'),
        ),
    ]
