# Generated by Django 6.0 on 2026-09-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_copy_national_code_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='national_code',
        ),
    ]
