# Generated by Django 6.0 on 2026-10-05 21:30

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_initial'),
        ('school', '0006_assign_subject_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('event_type', models.CharField(choices=[('official', 'تعطیل رسمی'), ('unplanned', 'تعطیلی غیرمنتظره')], default='official', max_length=20, verbose_name='نوع')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(help_text='برای تعطیلی یک\u200cروزه همان تاریخ شروع را وارد کنید.', verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_events', to='school.academicyear', verbose_name='سال تحصیلی')),
                ('bells', models.ManyToManyField(blank=True, help_text='خالی یعنی همه\u200cی زنگ\u200cها (تعطیلی کامل روز).', related_name='calendar_events', to='scheduling.bell', verbose_name='زنگ\u200cها')),
                ('branches', models.ManyToManyField(blank=True, help_text='خالی یعنی همه\u200cی شعبه\u200cها.', related_name='calendar_events', to='school.branch', verbose_name='شعبه\u200cها')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('grades', models.ManyToManyField(blank=True, help_text='خالی یعنی همه\u200cی پایه\u200cها.', related_name='calendar_events', to='school.grade', verbose_name='پایه\u200cها')),
            ],
            options={
                'verbose_name': 'رویداد تقویم آموزشی',
                'verbose_name_plural': 'تقویم آموزشی (تعطیلات)',
                'ordering': ['-start_date', '-pk'],
                'indexes': [models.Index(fields=['academic_year', 'is_active', 'start_date', 'end_date'], name='calendar_event_range_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='calendar_event_end_after_start', violation_error_message='تاریخ پایان نباید قبل از تاریخ شروع باشد.')],
            },
        ),
    ]
