# Generated by Django 6.0 on 2026-07-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='teacher_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='staff.teacherassignment', verbose_name='معلم'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='school.branch', verbose_name='شعبه'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade', verbose_name='پایه'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear', verbose_name='سال تحصیلی'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='school.schoolclass', verbose_name='کلاس'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_subjects', to='school.subject', verbose_name='درس'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('branch', 'year', 'grade', 'section'), name='unique_class_per_branch_year_grade_section'),
        ),
        migrations.AddConstraint(
            model_name='classsubject',
            constraint=models.UniqueConstraint(fields=('school_class', 'subject', 'teacher_assignment'), name='unique_class_subject_teacher_assignment'),
        ),
    ]
