# Generated by Django 6.0 on 2026-07-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_branch_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'شعبه', 'verbose_name_plural': 'شعبه ها'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.SlugField(max_length=30, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن'),
        ),
    ]
