# Generated by Django 6.0 on 2026-09-26 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_branch_options_alter_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#d96a30', help_text='رنگ این درس در برنامه هفتگی و فایل PDF آن.', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='رنگ باید یک کد هگز شش\u200cرقمی مثل \u200e#2563eb\u200e باشد.', regex='^#[0-9a-fA-F]{6}\\Z')], verbose_name='رنگ'),
        ),
    ]
