# Generated by Django 6.0 on 2026-09-29 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_national_code_and_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ورود')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='مرورگر (کامل)')),
                ('browser', models.CharField(blank=True, default='', max_length=64, verbose_name='مرورگر')),
                ('os', models.CharField(blank=True, default='', max_length=64, verbose_name='سیستم\u200cعامل')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='کلید نشست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ورود',
                'verbose_name_plural': 'ورودها',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_activity_user_idx')],
            },
        ),
    ]
