# Generated by Django 6.0 on 2026-10-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_login_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'دانش آموز'), ('teacher', 'معلم'), ('supervisor', 'پشتیبان'), ('accountant', 'حسابدار'), ('counselor', 'مشاور'), ('it', 'انفورماتیک'), ('services', 'خدمات'), ('admin', 'مدیر سامانه'), ('director', 'مدیر مدرسه')], max_length=20, verbose_name='نقش'),
        ),
    ]
