# Generated by Django 6.0 on 2026-07-11 08:17

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ جلسه')),
                ('session_number', models.PositiveIntegerField(editable=False, verbose_name='شماره جلسه')),
                ('status', models.CharField(choices=[('JB', 'جبرانی'), ('CD', 'کنسل شده'), ('HD', 'برگزار شده')], default='HD', max_length=2, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='school.classsubject', verbose_name='درس کلاس')),
            ],
            options={
                'verbose_name': 'جلسه درسی',
                'verbose_name_plural': 'جلسات درسی',
                'ordering': ['-date', '-session_number'],
            },
        ),
        migrations.CreateModel(
            name='SessionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('activity', models.TextField(verbose_name='فعالیت')),
                ('homework', models.TextField(verbose_name='تکلیف')),
                ('notes', models.TextField(verbose_name='یادداشت\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='session_contents', to='teaching.schoolsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'محتوای جلسه',
                'verbose_name_plural': 'محتوای جلسات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolsession',
            constraint=models.UniqueConstraint(fields=('class_subject', 'session_number'), name='unique_session_number_per_class_subject'),
        ),
    ]
