# Generated by Django 6.0 on 2026-09-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncontent',
            name='activity',
            field=models.TextField(blank=True, verbose_name='فعالیت'),
        ),
        migrations.AlterField(
            model_name='sessioncontent',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها'),
        ),
    ]
