# Generated by Django 6.0 on 2026-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_assign_subject_colors'),
        ('teaching', '0002_optional_activity_and_notes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schoolsession',
            index=models.Index(fields=['class_subject', 'date'], name='school_session_cs_date_idx'),
        ),
    ]
