# Generated by Django 6.0 on 2026-10-05 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0001_initial'),
        ('scheduling', '0002_initial'),
        ('school', '0006_assign_subject_colors'),
        ('teaching', '0003_school_session_class_subject_date_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsession',
            name='bell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='scheduling.bell', verbose_name='زنگ'),
        ),
        migrations.AddField(
            model_name='schoolsession',
            name='calendar_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academic_calendar.calendarevent', verbose_name='رویداد تقویم'),
        ),
        migrations.AddField(
            model_name='schoolsession',
            name='is_auto_created',
            field=models.BooleanField(default=False, editable=False, help_text='جلسه\u200cای که تقویم آموزشی ساخته است، نه معلم.', verbose_name='ایجاد خودکار'),
        ),
        migrations.AlterField(
            model_name='schoolsession',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره جلسه'),
        ),
        migrations.AlterField(
            model_name='schoolsession',
            name='status',
            field=models.CharField(choices=[('JB', 'جبرانی'), ('CD', 'کنسل شده'), ('HD', 'برگزار شده'), ('HL', 'تعطیل')], default='HD', max_length=2, verbose_name='وضعیت'),
        ),
        migrations.AddConstraint(
            model_name='schoolsession',
            constraint=models.UniqueConstraint(condition=models.Q(('bell__isnull', False)), fields=('class_subject', 'date', 'bell'), name='unique_session_per_slot', violation_error_message='برای این درس در این زنگ و این تاریخ قبلاً جلسه ثبت شده است'),
        ),
        migrations.AddConstraint(
            model_name='schoolsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('session_number__isnull', True), ('status', 'HL')), models.Q(models.Q(('status', 'HL'), _negated=True), ('session_number__isnull', False)), _connector='OR'), name='session_number_only_when_counted'),
        ),
    ]
