# Generated by Django 6.0 on 2026-07-11 08:17

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=20, unique=True, verbose_name='کد دانش\u200cآموزی')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل دانش\u200cآموز',
                'verbose_name_plural': 'پروفایل دانش\u200cآموزان',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت\u200cنام')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('transferred', 'منتقل شده'), ('graduated', 'فارغ\u200cالتحصیل'), ('withdrawn', 'انصراف')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('academic_year', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='school.academicyear', verbose_name='سال تحصیلی')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='school.schoolclass', verbose_name='کلاس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='student.studentprofile', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دانش\u200cآموز',
                'verbose_name_plural': 'ثبت\u200cنام دانش\u200cآموزان',
                'ordering': ['-academic_year__start_date', 'student__user__last_name', 'student__user__first_name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_per_academic_year')],
            },
        ),
    ]
