# Generated by Django 6.0 on 2026-09-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد دانش\u200cآموزی'),
        ),
    ]
