# Generated by Django 6.0 on 2026-08-29 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0004_alter_branch_options_alter_branch_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='school.grade', verbose_name='پایه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل پشتیبان',
                'verbose_name_plural': 'پروفایل\u200cهای پشتیبان',
            },
        ),
        migrations.CreateModel(
            name='SupervisorClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignments', to='school.schoolclass', verbose_name='کلاس')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='supervisor.supervisorprofile', verbose_name='پشتیبان')),
            ],
            options={
                'verbose_name': 'کلاس تحت نظارت',
                'verbose_name_plural': 'کلاس\u200cهای تحت نظارت',
                'constraints': [models.UniqueConstraint(fields=('supervisor', 'school_class'), name='unique_supervisor_school_class')],
            },
        ),
    ]
