# Generated by Django 6.0 on 2026-08-29 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_branch_options_alter_branch_address_and_more'),
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisors', to='school.branch', verbose_name='شعبه'),
        ),
    ]
