# Generated by Django 6.0 on 2026-07-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('student', '0001_initial'),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='teaching.schoolsession', verbose_name='جلسه'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='student.studentenrollment', verbose_name='ثبت\u200cنام دانش\u200cآموز'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('session', 'student_enrollment'), name='unique_attendance_per_session'),
        ),
    ]
